services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    ports:
      - 8123:8123
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: true
    networks:
      - private

  nginx:
    container_name: nginx
    image: "nginx"
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/conf/htpasswd:/etc/nginx/conf/htpasswd:ro
      - ./public:/usr/share/nginx/html:ro
      - ./certbot/conf/:/etc/nginx/ssl:ro
    networks:
      - private
    ports:
    - 443:443
    - 80:80
    env_file:
      - .env

# Это позволяет контейнерам взаимодействовать друг с другом по именам сервисов (нужно указать сеть private у каждого контейнера)
networks:
  private:
    driver: bridge
