# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# https://www.home-assistant.io/integrations/http/
http:
  server_port: 8080
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/12
  ip_ban_enabled: true
  login_attempts_threshold: 3

# telegram_bot:
#   - platform: polling
#     api_key: <api_key>
#     allowed_chat_ids:
#       - <channel_id>

# notify:
#   - name: telegram_notifier
#     platform: telegram
#     chat_id: <channel_id>

media_player:
  - platform: vlc

media_dirs:
    media: /media
